
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhkkzjprtrpwahhaygqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoa2t6anBydHJwd2FoaGF5Z3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTMzNTMsImV4cCI6MjA2MDE4OTM1M30.4eXiSAfAEpSLOpveqE5ZMuR1danMM3H7-wbYLqUKTc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    fetch: (url, options) => {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000); // 15 second timeout
      
      return fetch(url, {
        ...options,
        signal: controller.signal,
      }).finally(() => clearTimeout(timeoutId));
    },
  },
});

// Utility function to check if Supabase is available
export const checkSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('files').select('count').limit(1);
    return !error;
  } catch (err) {
    console.error('Failed to connect to Supabase:', err);
    return false;
  }
};

// Generate a shareable link for files
export const generateShareableLink = (fileId: string) => {
  const baseUrl = window.location.origin;
  return `${baseUrl}/shared/${fileId}`;
};

// Verify if a shared file is accessible
export const verifySharedAccess = async (fileId: string) => {
  try {
    const { data, error } = await supabase
      .from('files')
      .select('*')
      .eq('id', fileId)
      .or(`is_public.eq.true,shared_with.cs.'{anonymous}'`)
      .maybeSingle();
      
    if (error) throw error;
    return !!data;
  } catch (error) {
    console.error('Error verifying shared access:', error);
    return false;
  }
};
